"""
HuRI Adapter for BioCypher.

Loads Human Reference Interactome (HuRI) binary protein-protein interactions
and generates:
- ReferenceInteraction edges (experimentally determined binary PPIs)

HuRI is a systematic binary protein-protein interaction map of the human
proteome generated by yeast two-hybrid screening.
"""

from pathlib import Path
from biocypher._logger import logger


class HuRIAdapter:
    def __init__(self, data_dir="template_package/data/huri"):
        self.data_dir = Path(data_dir)
        self.interactions = []
        self._load_data()

    def _sanitize(self, text):
        if text is None:
            return ""
        text = str(text)
        text = text.replace('"', '""')
        text = text.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')
        return text.strip()

    def _load_data(self):
        """Load HuRI interaction data."""
        # Prefer HuRI.tsv (the main reference interactome)
        path = self.data_dir / 'HuRI.tsv'
        if not path.exists():
            path = self.data_dir / 'HI-union.tsv'
        if not path.exists():
            logger.warning("HuRI: interaction data not found")
            return

        logger.info(f"HuRI: Loading interactions from {path.name}...")
        seen = set()
        count = 0

        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) < 2:
                    continue

                gene_a = parts[0].strip()
                gene_b = parts[1].strip()

                if not gene_a or not gene_b:
                    continue

                # Normalize order for deduplication
                key = tuple(sorted([gene_a, gene_b]))
                if key in seen:
                    continue
                seen.add(key)

                self.interactions.append({
                    'gene_a': gene_a,
                    'gene_b': gene_b,
                })
                count += 1

        logger.info(f"HuRI: Loaded {count} binary interactions")

    def get_nodes(self):
        """No new nodes."""
        logger.info("HuRI: No new nodes")
        return iter([])

    def get_edges(self):
        """
        Generate ReferenceInteraction edges.
        Yields: (id, source, target, label, properties)
        """
        logger.info("HuRI: Generating edges...")
        count = 0

        for interaction in self.interactions:
            props = {
                'detection_method': 'yeast two-hybrid',
                'source': 'HuRI',
            }

            yield (
                None,
                interaction['gene_a'],
                interaction['gene_b'],
                "ReferenceInteraction",
                props
            )
            count += 1

        logger.info(f"HuRI: Generated {count} ReferenceInteraction edges")
